<table>
    <thead>
        <th>ID</th>
        <th>Titre</th>
        <th>Contenu</th>
        <th>Catégorie</th>
        <th>auteur</th>
        <th>actif</th>
    </thead>
    <tbody>
        <?php foreach($tasks as $task): ?>
            <tr>
                <td><?= $task->id ?></td>
                <td><?= $task->title ?></td>
                <td><?= $task->description ?></td>
                <td><?= $task->category_id ?></td>
                <td><?= $task->author_id ?></td>
                <td><?= $task->active ?></td>
                <td>
                    <a href="index.php?p=admin/activeTask/<?= $task->id ?>" >Activer/Désativer</a>
                    <a href="index.php?p=tasks/update/<?= $task->id ?>" >Modifier</a>
                    <a href="index.php?p=admin/deleteTask/<?= $task->id ?>" >Supprimer</a>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>