<table>
    <thead>
        <th>ID</th>
        <th>Pseudo</th>
        <th>Roles</th>
    </thead>
    <tbody>
        <?php foreach($users as $user): ?>
            <tr>
                <td><?= $user->id ?></td>
                <td><?= $user->username ?></td>
                <td><?= $user->roles ?></td>
                <td>
                    <a href="index.php?p=admin/deleteUser/<?= $user->id ?>" >Supprimer</a>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<input type="button" value="RETOUR" onclick="history.back();">