
<footer>
        <div class="bloc footer-medias">
          <h3>Nos réseaux</h3>
          <ul class="liste-media">
            <li>
              <a href="#">
                <img src="src/ressources/facebook.svg" alt="icone réseaux sociaux">
              </a>
            </li>
            <li>
              <a href="#">
                <img src="src/ressources/insta.svg" alt="icone réseaux sociaux">
              </a>
            </li>
            <li>
              <a href="#">
                <img src="src/ressources/twitter.svg" alt="icone réseaux sociaux">
              </a>
            </li>
            <li>
              <a href="#">
                <img src="src/ressources/globe-internet.svg" alt="icone réseaux sociaux">
              </a>
            </li>
            <li>
              <a href="#">
                <img src="src/ressources/linkedin.svg" alt="icone réseaux sociaux">
              </a>
            </li>
          </ul>
        </div>
        <p>Site créé par Yohann HOURY - 2022</p>
</footer>
          

