<div class="identification">
  <?php if(isset($_SESSION['connected']) && $_SESSION['connected'] == true): ?>
    <img class="avatar" src="public/uploads/users/<?= $_SESSION['user']['avatar']?>" alt="Image avatar">
    <h5>Bonjour <?= $_SESSION['user']['firstName'].' '.$_SESSION['user']['lastName']?></h5>
  <?php else: ?>
    <img class="avatar" src="public/uploads/users/silhouette.png" alt="Image silhoutte">
    <h5>Merci de bien vouloir vous identifier SVP !</h5>
  <?php endif; ?>
</div>

