<h1>Création d'un compte !</h1>

<form enctype="multipart/form-data" action="index.php?road=addUser" method="POST">
    <legend>Merci de renseigner les information suivantes :</legend>
    <?php require_once('_errors.phtml');?>
    <?php require_once('_valids.phtml');?>

    <label for="firtName">Entrez votre nom</label>
    <input type="text" name="firstName" size="30">

    <label for="lastName">Entrez votre prénom</label>
    <input type="text" name="lastName" size="30">

    <label for="email">Entrez votre email</label>
    <input type="text" name="email" size="30">

    <label for="password">Choisissez un mot de passe</label>
    <div><input type="password" name="password" id="password_1" size="30" style="width: 90%"><button id="eyes1"><i id="eyesImag1" class="fas fa-eye-slash"></i></button></div>

    <label for="password_verify">Confirmez le mot de passe choisi</label>
    <div><input type="password" name="password_confirme" id="password_2" size="30" style="width: 90%"><button id="eyes2"><i id="eyesImag2" class="fas fa-eye-slash"></i></button></div>

    <label for="userfileAvatar">Votre avatar : </label>
    <input type="file" accept="image/*" name="userfileAvatar">
    <small class="form-text text-muted">Sélectionnez une image : Formats ['jpg', 'jpeg', 'gif', 'png'].</small>

    <input type="submit" value="Valider"/>

</form>



