
<?php if(!empty($article)): ?>

	<section class="intro">
		<h1><?= htmlspecialchars($article['art_title']) ?></h1>
	</section>
	<section>
		<article>
			<section class="detailsArticle">
				<div>
					<img src="public/uploads/img_Of_Articles/<?= htmlspecialchars($article['art_img']) ?>" alt="image">
					<i class="fas fa-star"></i>Sortie prévue : <?= htmlspecialchars(date_format(date_create(($article['art_date_sortie'])), 'd/m/Y'))?><br>
					<i class="fas fa-star"></i><?= htmlspecialchars($article['art_price']) ?> €
				</div>
				<div>
					<p class="textDescription"><?= nl2br(htmlspecialchars($article['art_description'])) ?></p>
				</div>
			</section>
		</article>
	</section>

	<section class="listImg">
		<?php if(!empty($allImages)): ?>
			<?php foreach($allImages as $img): ?>
				<div>
					<img src="public/uploads/all_Img_Of_Articles/<?= htmlspecialchars($img['img_root']) ?>" alt="Image" class="imgDetails">
				</div>
			<?php endforeach; ?>
		<?php else: ?>
			<h2>Aucune image disponible actuellement pour cette figurine !</h2>
		<?php endif; ?>
	</section>

<?php else: ?>
	<h2>Aucun article n'a été trouvé !</h2>
<?php endif; ?>