<h1>Ajout d'une activité !</h1>

<form enctype="multipart/form-data" action="index.php?path=submitFormAddArticle" method="POST">
    <legend>Merci de renseigner les information suivantes :</legend>

    <?php require_once('_errors.phtml');?>
    <?php require_once('_valids.phtml');?>

    <label for="categorie">Catégorie de l'article :</label>
    <select name="categorie" class="categorie">
        <option value="">CATEGORIE</option>
        <?php foreach($categories as $cat): ?>
            <option value="<?= htmlspecialchars($cat['cat_id']) ?>"
                <?php if(isset($addArticle['addCategorie']) && $addArticle['addCategorie'] == $cat['cat_id']) :?>
                    selected
                <?php endif; ?>
            ><?= htmlspecialchars($cat['cat_title']) ?></option>
        <?php endforeach; ?>
    </select>

    <label for="name">Titre :</label>
    <input  type="text"
            name="title"
            value="<?php if(isset($addArticle['addtitle'])) {
                            echo htmlspecialchars($addArticle['addtitle']);
                        } ?>">

    <label for="user_name">Sous-titre :</label>
    <input  type="text"
            name="underTitle"
            value="<?php if(isset($addArticle['addUnderTitle'])) {
                            echo htmlspecialchars($addArticle['addUnderTitle']);
                        } ?>">

    <label for="story">Description :</label>
    <textarea id="story" name="story" rows="5" cols="33"></textarea>

    <label for="start">Date de sortie :</label>
    <input type="date" id="start" name="date_start">

    <label for="price">Prix :</label>
    <input type="number" name="price" step="0.01" min="0" max="500">

    <fieldset>
        <label for="imag_article">Image principale : </label>
        <input type="file" accept="image/*" name="imag_article" id="imag_article" class="flyover">
        <small class="form-text text-muted">Sélectionnez une image : Formats ['jpg', 'jpeg', 'gif', 'png'].</small></br>
	    <small class="form-text text-muted">Dimensions de l'image : [500px * 531px].</small>
    </fieldset>

    <input type="submit" value="Valider"/>
</form>