<!DOCTYPE html>
<html lang="fr">

<head>
    <?php $head ?>
</head>
<body>
    <header>
         <?php if(!empty($_SESSION['erreur'])): ?>
            <div class="erreur">
                <?php echo $_SESSION['erreur']; unset($_SESSION['erreur']); ?>
            </div>
        <?php endif; ?>
        <?php if(!empty($_SESSION['message'])): ?>
            <div class="message">
                <?php echo $_SESSION['message']; unset($_SESSION['message']); ?>
            </div>
        <?php endif; ?>
    </header>
    <main class="container">
        <?= $content ?>
    </main>
     <?php $footer ?>
</body>    
</html>