<!DOCTYPE html>
<html lang="fr">

<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="description" content="LE FORUM DES MYTH CLOTH">
	<title><?= TITLEPAGE ?></title>
	<link rel="icon" href="favicon.png">
	<link href="https://fonts.googleapis.com/css?family=Athiti:500|Merienda:400,700&display=swap" rel="stylesheet">
	<link rel="stylesheet" href="public/css/slick.css">
	<link rel="stylesheet" href="front/css/style.css">
</head>

<body>
	<header>
		<div class="container">
			<?php include $template ?>
		<span>
				<a href="index.php?route=home" class="logo">
					<img src="public/img/<?= IMGLOGO ?>" alt="Logo">
					<strong><?= TITLEPAGE ?></strong>
				</a>
			</span>
			<nav>
				<!-- <div class="blocSearch">
					<input type="text" id="search" autocomplete="off" placeholder="Rechercher un article avec son titre !">
					<div id="targetLabels"></div>
				</div> -->
				<?php require_once('_identification.phtml');?>
			</nav>
		</div>
	</header>

	<main class="container">
		
		<nav>
			<?php require_once('_ulNav.phtml'); ?>
		</nav>

	</main>

	<footer>
		<!-- En règle générale, le footer ne change pratiquement pas, il est donc judicieux de le mettre
			à part dans un fichier et de le requérir comme par exemple :

			<?php require_once('_footer.phtml'); ?>
		-->
	</footer>

	<!--<script src="public/js/main.js"></script>-->
</body>

</html>