<section class="task">
        <?php if(isset($_SESSION['user']['id']) == !empty($_SESSION['user']['id'])): ?>
            <?php foreach($tasks as $task): ?>
                <?php if(isset($_SESSION['user']['id']) == $task->author_id): ?>
                <article>
                    <a href="index.php?p=tasks/read/<?= $task->id ?>">
                    <h2><?= $task->title ?></a></h2>
                    <div><?= $task->description ?></div>
                    <div><?= $task->date ?></div>
                    <div>
                      <input type="checkbox" id="terminate" name="terminate[]" value="OK">
                      <a href="index.php?p=tasks/update/<?= $task->id ?>">Modifier</a>
                    <input type="submit" name="validate" value="valider">
                    </div>
                </article>
                 <?php endif; ?>
            <?php endforeach; ?>
        <?php endif; ?>
</section>
