<section>
<?php if(isset($_SESSION['user']['id']) == !empty($_SESSION['user']['id'] == $task->author_id)): ?>
         <h2>Modifier la tâche <?= $task->id ?></h2>
          <form action='#' method='post'>
              <label for='title'>Titre de la tâche :</label>
              <input type='text' name="title" id="title" value="<?= $task->title ?>">
              <label for='description'>Texte de la tâche</label>
              <textarea name='description' id="description"><?= $task->description ?></textarea>
              <button>Modifier</button>
              <input type="button" value="RETOUR" onclick="history.back();">
         </form>
<?php endif; ?>
</section>
