<section>
    <header>
        <h2>A propos</h2>
    </header>
    <main>
        <p>
            <span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci, blanditiis!</span>
            <span>Nemo, voluptatibus, nihil doloremque rerum molestiae reprehenderit odio sunt ipsum.</span>
            <span>Recusandae aut quae harum vero aliquam quos provident accusantium qui.</span>
            <span>Ipsum, molestias consequatur vero quod nobis deleniti ullam harum vitae.</span>
        </p>
    </main>
</section>