<section>
    <header class="about">
        <h1><?= $pages['content'] ?></h1>
                <nav>
                    <ul class="layout__ul">
                        <li>
                            <a href="index.php">Accueil</a>
                        </li>
                    </ul>
                </nav>
    </header>
    <main>
        <p>
            <span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci, blanditiis!</span>
            <span>Nemo, voluptatibus, nihil doloremque rerum molestiae reprehenderit odio sunt ipsum.</span>
            <span>Recusandae aut quae harum vero aliquam quos provident accusantium qui.</span>
            <span>Ipsum, molestias consequatur vero quod nobis deleniti ullam harum vitae.</span>
        </p>
    </main>
</section>