<section class="account">
    <header>
        <h2>Bienvenu sur votre compte<!-- mettre le lien php vers le username-->    </h2>
    </header>
    <aside>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Temporibus, fugiat?</p><!--mettre les activités en cours-->
    </aside>
    <main>
        <menu>
          <article class="cards">
             <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur, voluptatem, hic, cumque tempore iure quidem deserunt dignissimos magnam non temporibus eveniet distinctio repellat numquam ratione dicta amet vel. Necessitatibus, debitis, maiores totam consequuntur magnam quos reiciendis animi mollitia praesentium! Cupiditate.</p> <!--compteur d'activités-->
          </article>
          <article class="cards">
             <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Temporibus, fugiat?</p> <!-- Knock knock Neo ... -->
          </article>
          <article class="cards">
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Temporibus, fugiat?</p>
          </article>
          <article class="cards">
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Temporibus, fugiat?</p>
          </article>
          <article class="cards">
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Temporibus, fugiat?</p>
          </article> 
        </menu>
    </main>

</section>