<section>
    <header>
        <h2>CONTACT</h2>
    </header>
    <main>
        <p>
            <span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci, blanditiis!</span>
            <span>Nemo, voluptatibus, nihil doloremque rerum molestiae reprehenderit odio sunt ipsum.</span>
            <span>Recusandae aut quae harum vero aliquam quos provident accusantium qui.</span>
            <span>Ipsum, molestias consequatur vero quod nobis deleniti ullam harum vitae.</span>
            <span>Sapiente ab error alias nemo quod consectetur commodi voluptas aliquid.</span>
            <span>Eligendi, quod, alias ipsum et provident nulla perferendis rerum esse.</span>
            <span>Illo, fuga beatae assumenda officia eaque. Voluptates error ex doloremque.</span>
            <span>A, magni molestiae perspiciatis eius assumenda ratione inventore recusandae qui!</span>
            <span>Quis, dolor, non voluptatem atque quod est neque nostrum aliquam.</span>
            <span>Rerum, voluptate ipsum illum non quas corporis iste ipsam quos.</span>
        </p>
        
        
    </main>
    
    
    
    
</section>