
<section class="home">

<header class="home__header" >
    
     <h1><?= $pages['title']; ?></h1>
     
</header>
    
 <nav>
         <ul> 
            <li>
            <a href="index.php?path=login">
            <h3>CONNEXION</h3>
            </a> 
            </li>
            
            <li >
            <a href="index.php?path=registration">
            <h3>INSCRIPTION</h3>
            </a> 
            </li>
            
            <li>
            <a href="index.php?path=about">
            <h3>A PROPOS</h3>
            </a> 
            </li>
            
            <li>
            <a href="index.php?path=contact">
            <h3>CONTACT</h3>

            </a> 
            </li>
        </ul>  
    </nav>
</section>