<section class="home_menu">
    <div>
        <figure class="loginFigure">
        <img src="./front/ressources/login.svg" alt="image de connexion à l'application">
        <!--<figcaption>Connexion au compte</figcaption>-->
         <a href="index.php?path=login" class="home-btn">Connexion</a>   
        </figure>
        <figure class="loginFigure">
        <img src="./front/ressources/login.svg" alt="image de connexion à l'application">
        <!--<figcaption>Connexion au compte</figcaption>-->
          <a href="index.php?path=registration" class="home-btn">Inscription</a>   
        </figure>
        <figure class="loginFigure">
        <img src="./front/ressources/login.svg" alt="image de connexion à l'application">
        <!--<figcaption>Connexion au compte</figcaption>-->
         <a href="index.php?path=about" class="home-btn">à propos</a>   
        </figure>
        <figure class="loginFigure">
        <img src="./front/ressources/login.svg" alt="image de connexion à l'application">
        <!--<figcaption>Connexion au compte</figcaption>-->
         <a href="index.php?path=contact" class="home-btn">contact</a>   
        </figure>
    </div>
</section>