
<section class="home">

<header class="home__header" >
    <p><?= $pages['content']; ?></p>
</header>

    
 <nav "home__nav">
            
            <a href="index.php?path=login">
            <button class="home__nav__btn">
            <h3>CONNEXION</h3>
            </button>
            </a> 
            
            <a href="index.php?path=registration">
            <button class="home__nav__btn">
            <h3>INSCRIPTION</h3>
            </button>
            </a> 
             
            <a href="index.php?path=about">
            <button class="home__nav__btn">
            <h3>A PROPOS</h3>
            </button>
            </a> 
            
            <a href="index.php?path=contact">
            <button class="home__nav__btn">
            <h3>CONTACT</h3>
            </button>
            </a> 
    </nav>
</section>