<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <title><?= $pages['title']; ?></title>
        <meta name="description" content=<?= $pages['content']; ?>  >
        <!--<link rel="stylesheet" href="front/css/style.css">-->
        <link href="http://fonts.cdnfonts.com/css/petit-formal-script" rel="stylesheet">
    </head>
    <body>
     <?php require "./templates/".$pages['route'].".phtml"; ?>
    </body>
</html>