<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <title>Late'Motiv</title>
        <link rel="stylesheet" href="front/css/style.css" type="text/css" />
    </head>
    <body>
        <header class="container_header">
            <h1>LATE'MOTIV</h1>
        </header>
        <main class="container">
            <?php require "./templates/".$page.".phtml"; ?>
        </main>
        <footer class="container_footer">
            <small>Application et Site Créés par Yohann HOURY</small>
        </footer>
    </body>
</html>