
        <section class="login">
            <header class="login__header" >
             <h1><?= $pages['title'] ?></h1>
                <nav>
                    <ul>
                        <li>
                            <a href="index.php">Accueil</a>
                        </li>
                    </ul>
                </nav>
            </header>
            
            <form method="POST">
                
               <fieldset class="login__fieldset"> 
                
            <div>
              <p>
                    <label>Nom d'utilisateur</label>
              </p>
              <p>    
                    <input type="text" placeholder="Entrer le nom d'utilisateur" name="username">
              </p>
            </div>
                
            <div>
                <p>
                    <label>Mot de passe</label>
                </p>
                <p>
                    <input type="password" placeholder="Entrer le mot de passe" name="password">
                </p>
            </div>
                
            <p>   
                <input type="submit" id='submit' value='VALIDER' >
            <p/>
                
                <!--?php-->
                <!--if(isset($_GET['erreur'])){-->
                <!--    $err = $_GET['erreur'];-->
                <!--    if($err==1 || $err==2)-->
                <!--        echo "<p style='color:red'>Utilisateur ou mot de passe incorrect</p>";-->
                <!--}-->
                <!--?>-->
               </fieldset>
            </form>
        </section>
