
        <section class="login">
            
            <form action="verification.php" method="POST">
                
               <fieldset class="login__fieldset"> 
               
                <label>Nom d'utilisateur</label>
                <input type="text" placeholder="Entrer le nom d'utilisateur" name="username">
    
                
            
                <label>Mot de passe</label>
                <input type="password" placeholder="Entrer le mot de passe" name="password">
            
                
               
                <input type="submit" id='submit' value='VALIDER' >
            
                
                <!--?php-->
                <!--if(isset($_GET['erreur'])){-->
                <!--    $err = $_GET['erreur'];-->
                <!--    if($err==1 || $err==2)-->
                <!--        echo "<p style='color:red'>Utilisateur ou mot de passe incorrect</p>";-->
                <!--}-->
                <!--?>-->
               </fieldset>
            </form>
        </section>
