<section class="registration">
     <h1><?= $pages['content']; ?></h1>
    <form method=POST >
        <fieldset class="registration--fieldset">
        <div>
            <p>
                <label>prénom </label>
            </p>
            <p>        
                <input type="text" first_name=""/>
            </p>    
        </div>
        <div>
            <p>
                <label>nom </label>
            </p>
            <p>        
                <input type="text" last_name=""/>
            </p>    
        </div>
        <div>
            <p>
                <label>Adresse courriel </label>
            </p>
            <p>
                <input type="text" email=""/>
            </p>    
        </div>
        <div>
            <p>
                <label>Pseudo </label>
            </p>
            <p>        
                <input type="text" pseudo=""/>
            </p>    
        </div>
        <div>
            <p>
                <label>Mot de passe </label>
            </p>
            <p>        
                <input type="password" password=""/>
            </p>
        </div>
        <div>
            <p>
                <input type="submit" value="VALIDER"/>
            </p>    
        </div>
        </fieldset>
    
    </form>

</section>    
    