<section class="registration">

    <form method=<?php $_GET ?> >
        <fieldset class="registration__fieldset">
        <div>
            <label>prénom </label>
            <input type="text" first_name=""/>
        </div>
        <div>
            <label>nom </label>
            <input type="text" last_name=""/>
        </div>
        <div>
            <label>Adresse courriel </label>
            <input type="text" email=""/>
        </div>
        <div>
            <label>Pseudo </label>
            <input type="text" pseudo=""/>
        </div>
        <div>
            <label>Mot de passe </label>
            <input type="password" password=""/>
        </div>
        <div>
            <input type="submit" value="VALIDER"/>
        </div>
        </fieldset>
    
    </form>

</section>    
    