<section class="registration">
     <h1><?= $pages['title'] ?></h1>
                <nav>
                    <ul class="layout__ul">
                        <li>
                            <a href="index.php">Accueil</a>
                        </li>
                    </ul>
                </nav>
    <form method=POST >
        <fieldset class="registration__fieldset">
        <div>
            <p>
                <label>adresse courriel </label>
            </p>
            <p>
                <input type="text" name="email" email=""/>
            </p>    
        </div>
        <div>
            <p>
                <label>Pseudo </label>
            </p>
            <p>        
                <input type="text" name="pseudo" pseudo=""/>
            </p>    
        </div>
        <div>
            <p>
                <label>Mot de passe </label>
            </p>
            <p>        
                <input type="password" name="passwordl" password=""/>
            </p>
        </div>
        <div>
            <p>
                <input type="submit" value="VALIDER"/>
            </p>    
        </div>
        <?php var_dump($_POST); ?>
        </fieldset>
    
    </form>

</section>    