<section>

  <div>
    <h2>LATE MOTIV</h2>
    <p>L'application anti-procrastination</p>
  </div>
  <form action="#" method="POST">
    <h2>Connexion</h2>
    <ul>
      <li>
        <label for="username"></label>
        <input type="text"  id="username" name="username" placeholder="Nom d'utilisateur" value="" required/>
      </li>
      <li>
        <label for="password"></label>
        <input type="password"  id="password" name="password" placeholder="Mot de passe" value="" required/>
      </li>
      <li>
        <input type="submit" id="btn-form" name="join" alt="Join" value="se connecter">
      </li>
    </ul>
  </form>
</section>