<section>
  <div>
    <h2>LATE MOTIV</h2>
    <p>L'application anti-procrastination</p>
  </div>
  <h2>INSCRIPTION</h2>
  <form action="" method="POST">
    <ul>
      <li>
        <label for="username"></label>
        <input type="text"  id="username" name="username" placeholder="Nom d'utilisateur"  required/>
      </li>
      <li>
        <label for="email"></label>
        <input type="email"  id="email" name="email" placeholder="adresse mail"  required/>
      </li>
      <li>
        <label for="pass"></label>
        <input type="password"  id="pass" name="password" placeholder="Mot de passe"  required/>
      </li>
      <li>
        <input type="submit" id="btn-form" name="join" alt="Join" value="s'inscrire">
      </li>
    </ul>
  </form>
    <a href="index.php?p=users/login">Déjà inscrit - Me connecter</a>
</section>