<!doctype html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name=description content="layout principal">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <link rel="stylesheet" href="./front/css/style.css" type="text/css" />
    <title><?php $title ?></title>
</head>
<body>
    <header class="container_header">
    <?php include "./views/template/header.phtml"; ?>
    <?php include "./views/template/menu.phtml"?>
    </header>
    <main class="container">
     <?php include "./views/template/".$page.".phtml"; ?>   
    </main>
    <footer class="container_footer">
    <?php include "./views/template/footer.phtml"; ?>
    </footer>
</body>
</html>